name: AndroidBuild

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'


      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Decode google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 --decode > /home/runner/work/Ecommerce-Admin_App/Ecommerce-Admin_App/app/src/google-services.json


      - name: Build with Gradle
        run: ./gradlew build



